### ISSUE TITLE
Add support for error-supression annotations

### ISSUE THREAD

**Issue by anroots** [psecio/parse#10]
Both phpcs and phpmd support special comments that suppress the reporting for certain files, checks or sections of a code.

This would be a good addition for reducing 'noise' for cases where you know an error will be reported, but you are aware of its implications and see no way around it (for example, if the file is auo-generated by some tool).

**Comment by redbeardcreator** [comment]
I'm starting to formulate a final plan for implementing this feature and I have a question about it. To what degree should the commandline options `--include-tests` and `--exclude-tests` override annotations?

I can see two paths:

1. The `--exclude-tests` and `--include-tests` are just used for building the overall list of available tests. If a test isn't in the list generated by discarding excluded tests and keeping only included tests, it cannot be run. But it can be disabled temporarily using annotations.

2. Excluded tests are completely removed from testing. Included tests are forced to be run, regardless of any annotations. Not excluded but not included tests can be turned on and off.

As things sit right now, I believe option 1 is the easiest. This is the way include and exclude work right now (i.e. `$list = includeFilter(excludeFilter($available, $exclude), $include);`). Annotations will just sit on top of that.

Option 2 will be harder to implement, simply because the meaning of `--include-tests` will need to be modified to mean "always include these, even if told otherwise" rather than "only include these, discarding all others."

Either way works for me, I just don't know which to go with. My initial thought (before looking at how the options work now) was to use option 2, but I think they are equally valid.

**Comment by hanneskod** [comment]
Hm, I'd say number 1.

I have an idea that the list of available tests could be compiled in more ways: custom tests could be added, tests could be grouped and added/removed as phpmd's ruleset option. This would be something you'd do at runtime, by specifying command line options. Annotations on the other hand are part of the code. For me it feels right that changing the runtime changes what results we produce, but changing the code shouldn't change the runtime...

To truly force a test to be used we could add a `--ignore-annotations` option.

**Comment by enygma** [comment]
Agreed, #1 sounds better and makes a bit more sense conceptually (imagine trying to explain the other one in just a README). and a +1 on that new option too. There does need to be something that people can use to "override all" just in case.

**Comment by redbeardcreator** [comment]
Then that's what I'll start to work on. I'll include the `--ignore-annotations` option.

**Comment by redbeardcreator** [comment]
Closed by #52
