### ISSUE TITLE
Changing the name of the executable

### ISSUE THREAD

**Issue by hanneskod** [psecio/parse#39]
I am installing parse globally so that I can use it to scan projects as part of a generic CI process. This means that the executed command will be something like:

```
parse scan directory
```

Now I am thinking that the name `parse` isn't ideal. Parse could mean just about anything, and there is a possibility of a name conflict. So I'm suggesting to rename the executable `psecio-parse`.

It is of course not very nice to our users to rename to executable. But if it should be done at all, it should be now when the tool is not stable. We could also provide a simple alias so that using the `parse` command still would work, but complain that `parse` is a deprecated name.

The good thing with using a name like `psecio-parse` is that there is no need to rename the repository or the composer package. I think it makes perfect sense for a cli tool named `psecio-parse` to be installed as `psecio/parse` (I was contemplating other names as well, but this is the reason I think `psecio-parse` is the best option).

@enygma @redbeardcreator What are your thoughts on this?

**Comment by enygma** [comment]
hmm, not sure about this one - seems like since that's the name of the tool the command should be kept the same. I see how just "parse" could be ambiguous, but I think most people using it will know what it is.

@redbeardcreator?

**Comment by redbeardcreator** [comment]
I'm going to straddle the fence on this one, unless Composer prevents it ;)

If it's installed globally, I'd want it to be installed as `psecio-parse`. I say this for a couple reasons. First, in general I don't want to have to think about renaming it if I have something else that is called parse. Second, Debian (my Linux distro of choice) would rename it to something like that if there was a conflict. While I'll probably only install it via Composer, if I installed it via aptitude, I wouldn't want the name to change. That said, a quick check of Debian's repository doesn't show any conflicts (I think...there are five files named "`parse`" or "`Parse`", but none are initially on the path and only one might be). On the other hand, there are lots of `xyz-parse`- or `abcparse`-type commands listed.

However, I can completely go with calling it `parse` in the local `bin` directory. So if it can be called `parse` there and `psecio-parse` globally, that would be the best. Otherwise, `psecio-parse`.

**Comment by hanneskod** [comment]
Hm, tricky. What I was thinking means changing the global name as well as the local (so it would be `bin/psecio-parse` in this repo).

The `composer global require ...` trick really is just a shorthand for adding a requirement to a package located at `~/.composer/`. And then to make whatever is installed in this package availiable globally you add `~/.composer/vendor/bin` to your path. There is no difference between how composer handles executables locally or globally.

**Comment by redbeardcreator** [comment]
Then to me, I'd say name it `psecio-parse`. Or something similar. If you support global installation, you should play nicely in the global namespace. Not everyone is on the cutting edge using Vagrant boxes and the like ;)

**Comment by enygma** [comment]
Okay, I'm okay with the name change - we just need to be very sure it's mentioned in the README and noted in the next release's notes.

**Comment by hanneskod** [comment]
Cool, I'll do a pr..
